import type { ChronicleEvent } from '@/types';

// Sorted chronologically. New events: append + re-sort by date.
export const chronicles: ChronicleEvent[] = [
  {
    id: 'hs-start',
    date: '2020-09-01',
    type: 'education',
    title: 'Started THPT Gia Định',
    description: 'High school years — STEM track.',
  },
  {
    id: 'hs-grad',
    date: '2023-06-01',
    type: 'education',
    title: 'Graduated High School',
    org: 'THPT Gia Định',
    description: 'GPA 9.5/10 · ĐGNL 820 · THPTQG 25.2',
  },
  {
    id: 'khaitam',
    date: '2023-08-01',
    type: 'role',
    title: 'Part-time Educator',
    org: 'Khai Tâm Tutoring Center',
    description: 'Tutoring math + STEM for high school students.',
    ongoing: true,
  },
  {
    id: 'iu-start',
    date: '2023-09-01',
    type: 'education',
    title: 'Started BSc Data Science',
    org: 'International University, VNU-HCM',
    description: 'Year 1.',
  },
  {
    id: 'gdgoc-member',
    date: '2024-09-01',
    type: 'role',
    title: 'Joined GDGoC HCMIU',
    description: 'Member of Google Developer Groups on Campus.',
  },
  {
    id: 'gdgoc-vicelead',
    date: '2025-08-01',
    type: 'role',
    title: 'Promoted to Vice Lead Chapter',
    org: 'GDGoC HCMIU · Gen 5',
    description: 'Term 2025–2026.',
  },
  {
    id: 'techtalk-2025',
    date: '2025-11-15',
    type: 'event',
    title: 'Hosted TechTalk · AI Chatbots × Blockchain',
    org: 'GDGoC HCMIU',
  },
  {
    id: 'iu-ai-2025',
    date: '2025-12-01',
    type: 'award',
    title: '3rd Place · IU AI Competition 2025',
  },
  {
    id: 'dengue-research',
    date: '2026-02-01',
    type: 'project',
    title: 'Started Dengue Shock Prediction Research',
    org: 'HTD HCMC × IU',
    description: 'IRB-approved · advisor Dr. Nguyễn Thị Thúy Loan.',
  },
  {
    id: 'swift-conf',
    date: '2026-04-15',
    type: 'event',
    title: 'Speaker · Swift Conference Vietnam',
  },
  {
    id: '100b-studio',
    date: '2026-04-15',
    type: 'project',
    title: 'Co-founded 100B Studio',
  },
  {
    id: 'enstudy-hub-v02',
    date: '2026-05-13',
    type: 'project',
    title: 'Shipped EnStudy-Hub v0.2.0',
    description: 'FSRS-4.5 vocab trainer · live on Vercel.',
  },
  {
    id: 'gdgoc-end',
    date: '2026-09-01',
    type: 'role',
    title: 'GDGoC term ends',
    description: 'Planned.',
  },
  {
    id: 'iu-grad',
    date: '2028-09-01',
    type: 'education',
    title: 'Expected Graduation',
    org: 'BSc Data Science · IU',
  },
];
